### ISSUE TITLE
Why is hpack looking for a YAML file?

### ISSUE THREAD

**Issue by schonfinkel** [fghibellini/nix-haskell-monorepo#1]
Hey @fghibellini! I'm following this great tutorial of yours but I've got stuck in the [Monorepo Nix Expressions](https://github.com/fghibellini/nix-haskell-monorepo/tree/master/monorepo-nix-expressions) part. 

Running the script causes the following error for me:
```
$ ./generate-packages.sh ../code
Clearing folder /<...>/nix-haskell-monorepo/monorepo-nix-expressions/monorepo/nix/packages
Reading packages in /<...>/nix-haskell-monorepo/monorepo-nix-expressions/monorepo/code
Generating Nix expression for package: hello-world (dir: /<...>/nix-haskell-monorepo/monorepo-nix-expressions/monorepo/code/hello-world)
*** hpack error: "../../code/hello-world/package.yaml: Yaml file not found: /<...>/nix-haskell-monorepo/monorepo-nix-expressions/monorepo/code/hello-world/package.yaml". Exiting.
Generating Nix expression for package: universe (dir: /<...>/nix-haskell-monorepo/monorepo-nix-expressions/monorepo/code/universe)
*** hpack error: "../../code/universe/package.yaml: Yaml file not found: /<...>/nix-haskell-monorepo/monorepo-nix-expressions/monorepo/code/universe/package.yaml". Exiting.
```

Deleting the `$HPACK` references in the script from: 
```
 (cd packages && cabal2nix $($WITH_HPACK && echo '--hpack') ../$CABAL_FILE_DIR > ./${PACKAGE_NAME}.nix && gitignore-src ./${PACKAGE_NAME}.nix)
```
to
```
(cd packages && cabal2nix ../$CABAL_FILE_DIR > ./${PACKAGE_NAME}.nix && gitignore-src ./${PACKAGE_NAME}.nix)
```

Seems to solve the issue for me, is `hpack` really needed in this section of the tutorial? 

Also, I'm running this on unstable `19.09pre180241.971b731fc18 (Loris)`. Thanks for making this project btw :+1: .

**Comment by fghibellini** [comment]
Thanks for reporting this!

`hpack` is really not needed, it's just the result of sloppy cleanup of the script from our work codebase.

thanks to feedback from other people I managed to come up with a solution that completely gets rid of the bash script to pre-generate the nix files and instead scans the `code` directory for cabal files at evaluation time. I plan to update the tutorial tomorrow.

I'm glad you like it :)

**Comment by fghibellini** [comment]
Just merged the changes. Please let me know if you have any other problems.

Thanks
