### ISSUE TITLE
Question about huge compilation time when running shell

### ISSUE THREAD

**Issue by santios** [fghibellini/nix-haskell-monorepo#5]
Hi Filippo. Thanks for this excellent tutorial.

In the second chapter, when I run this,

```bash
nix-shell -p '((import ./release.nix).haskellPackages.ghcWithPackages (pkgs: [ pkgs.universe ]))' --command "bash -c 'ghc-pkg list | grep universe'"
```

It starts compiling a huge amount of code. Not sure if it is compiling ghc again or what.

This is not the case if I run it with a normal package:

```sh
nix-shell -p '((import ./release.nix).haskellPackages.ghcWithPackages (pkgs: [ pkgs.text ]))' --command "bash -c 'ghc-pkg list | grep text'"
```

In that case, it does not compile anything.

Is this expected for overrides or am I doing something wrong?

Thanks! Any help appreciated.

**Comment by fghibellini** [comment]
If you manage to run the second command then the first one should definitely not recompile GHC (it's going to reuse the already built one).

It's more likely that it's building all the dependencies of `universe` (the dependency tree can be quite big).
When you run the command you should see right at the beginning an enumeration of all the derivations that are fetched from cache and the ones that will be built (I would expect the derivations already in your store - like GHC in you case - to not show up in either of the lists, but I haven't checked this behavior) e.g.

```
$ nix-shell -p '((import <nixpkgs> { config = { allowBroken = true; }; }).haskellPackages.ghcWithPackages (pkgs: [ pkgs.universe ]))' --command "bash -c 'ghc-pkg list | grep universe'"
these derivations will be built:
  /nix/store/cdlakpd665m9vpy3jd234yfcl733yqfl-universe-instances-extended-1.0.0.1.drv
  /nix/store/88clpacjkhl08rsc1r3n5rs0m94f68vg-universe-1.0.drv
  /nix/store/2ahfxqpyf4b2h2gfa7xdy9r34nrpgsbn-ghc-8.6.4-with-packages.drv
these paths will be fetched (0.31 MiB download, 3.55 MiB unpacked):
  /nix/store/24lkqpsks23dpdk016v6nc98a6cll46f-universe-instances-extended-1.0.0.1.tar.gz
  /nix/store/2k9al4pn86qpqr3i4lqpccabc0ia7i8a-universe-base-1.0.2.1-doc
  /nix/store/3rdbm80kd584yk4y5g1lnc9vb2smc5wb-universe-1.0.tar.gz
  /nix/store/45rnn6kxb8bslhaqm5i9fwhnivi6slw3-universe-instances-trans-1.0.0.1-doc
  /nix/store/5g1icgjm6bi7h1qa453yjmlsbdqycv20-universe-instances-trans-1.0.0.1
  /nix/store/kxi3r52gc571rdnay4nnc0s5ynv4w64w-universe-instances-base-1.0
  /nix/store/m7lddacyfz6wyvh3p0gd24s8dqxcfxkp-universe-instances-base-1.0-doc
  /nix/store/mdhkr9gli6p8pd5446fmcgrr52lszxwa-universe-instances-extended-1.0.0.1-r3.cabal
  /nix/store/w4hrgwbc5q3iylvaiij4kj3qyj1laibb-universe-reverse-instances-1.0
  /nix/store/w69n3ag5wbcniapiprjfrhaq2f83zqna-universe-base-1.0.2.1
  /nix/store/yaz564pvlnh25chjdxyl0qlv6zjv0f07-universe-reverse-instances-1.0-doc
...
```

especially if you overrode some library deep in the dependency tree it means that nothing that depended on it will be present in the cache end so you'll have to build it yourself.

**Comment by santios** [comment]
That makes sense, thanks @fghibellini
